#!/bin/bash

# aurdownload - download and extract packages from AUR
# Version: 1.0.8
# Author:  Michal Krenek (Mikos) <mikos@sg1.cz>
# License: GNU General Public License v.2
#          http://www.gnu.org/licenses/gpl.txt

if [ -z "$*" ]; then
  echo "aurdownload - download and optionally extract packages from AUR"
  echo "Error: You must specify package name(s)"
  exit 1
fi
EXTRACT=0
for name in "$@"; do
    if  [ $name == "-e" ]; then
	    EXTRACT=1
	    shift
    else
	echo "Removing old archive '$name.tar.gz'..."
	rm -f "$name.tar.gz"
	
	echo "Downloading package '$name'..."
	nameprefix=`echo $name|cut -c1-2`
	wget -nv "http://aur.archlinux.org/packages/$nameprefix/$name/$name.tar.gz"
	if [ $? -ne 0 ]; then
	    echo "Can't download '$name.tar.gz'. Skipping this package..."
	    echo 
	    continue
	fi
	if [ $EXTRACT = 1 ]; then
	    tar -xvzpf "$name.tar.gz" && rm "$name.tar.gz"
	fi
    fi
done

